version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    volumes:
      #- grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana-notifiers.yaml:/etc/grafana/provisioning/notifiers/notifiers.yaml
  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - c:\/:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
